### ISSUE TITLE
Change LinkPreview into a open source API

### ISSUE THREAD

**Issue by stilic** [malago86/flarum-linkpreview#2]
I have found a NPM package called [link-preview-generator](https://www.npmjs.com/package/link-preview-generator). We can host it for free on Heroku.

**Comment by malago86** [comment]
Do you know how we would do this? Is Heroku allowing cross-origin queries for the javascript? 

Could you try to deploy it on Heroku? After that, I can try to connect to it and see if it can access that information.

**Comment by stilic** [comment]
I have created [this](https://meta-grabber.herokuapp.com). You just need to add the option `url` with a URL to crawl.

**Comment by malago86** [comment]
Excellent! Thanks for the pull request, I will give it a try asap.

Also, I have seen that your Heroku app does not return an image from the website that is linked. Can you add that to the json? It should come on the attribute `image` for [this line](https://github.com/malago86/flarum-linkpreview/blob/main/js/src/forum/index.js#L50).

**Comment by justoverclockl** [comment]
maybe we can have finally a link preview extension with this :O

**Comment by stilic** [comment]
> Also, I have seen that your Heroku app does not return an image from the website that is linked. Can you add that to the json? It should come on the attribute `image` for [this line](https://github.com/malago86/flarum-linkpreview/blob/main/js/src/forum/index.js#L50).

It's work with images already: https://meta-grabber.herokuapp.com/?url=https://youtu.be/BVXxcbX0biM.

**Comment by malago86** [comment]
How come it does not work with Google or Twitter?

https://meta-grabber.herokuapp.com/?url=https://www.google.com
https://meta-grabber.herokuapp.com/?url=https://www.twitter.com

**Comment by stilic** [comment]
I don't say, sorry...
